version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\hansrodtang\runcom

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - git submodule update --init --recursive
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go build
  - go test -v ./...
